### ISSUE TITLE
Unsatisfied Link Error on M1 Macos 13

### ISSUE THREAD

**Issue by madhephaestus** [CommonWealthRobotics/mujoco-java#3]
Macos 13 throws an UnSatasfiedLinkError when executing. 

use https://github.com/actions/runner-images/issues/8439 to make a runner and build for the M1

**Comment by madhephaestus** [comment]
2.2.0-pre.11 adds this support in the stable release

**Comment by radeva** [comment]
Hi @madhephaestus,

Feel free to use [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one one and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hasitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)
